In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import cv2

In [2]:
#x,y,c,
ArabesqueCoords = np.load("RootCoordinates/ArabesqueX.npy")
print(ArabesqueCoords)
print(len(ArabesqueCoords))

[[0.579664 0.320268 0.892814 ... 0.497998 0.786081 0.773293]
 [0.581808 0.317562 0.895144 ... 0.502131 0.783505 0.774422]
 [0.577609 0.314789 0.909073 ... 0.497993 0.786139 0.77058 ]
 ...
 [0.559326 0.303823 0.90309  ... 0.477566 0.750626 0.749621]
 [0.55714  0.306521 0.948539 ... 0.481576 0.753467 0.676141]
 [0.563351 0.322821 0.977854 ... 0.318232 0.461866 0.587947]]
870


In [3]:
#What are the augmented features?
#Each samples' distances from the mean.
#Gather different feature configurations: 1 - distance from the mean, 2 Distance between significant points.

In [4]:
#Helper Methods:
import math
def calcDistance(x1,y1,x2,y2):
    distance = math.sqrt((x2-x1)**2 + (y2-y1)**2)
    return distance

#def calcDistVector(longZipFile, filename):
    #distanceVector = []
    #for ((x1,y1),(x2,y2)) in longZipFile:
        #d = calcDistance(x1,y1,x2,y2)
        #print(d)
        #distanceVector.append(d)
    #np.save(os.path.join('Stats', filename), distanceVector)

In [5]:
#Get the Mean Skeleton's coordinates
ArabesqueMeanX = np.load("Stats/ArabesqueMeanX.npy")
print(ArabesqueMeanX)
print(len(ArabesqueMeanX))
ArabesqueMeanY = np.load("Stats/ArabesqueMeanY.npy")
print(ArabesqueMeanY)
print(len(ArabesqueMeanY))
MeanTuples = list(zip(ArabesqueMeanX, ArabesqueMeanY))
print(MeanTuples)

[0.57181604 0.54940532 0.5305854  0.48819371 0.44590451 0.56942404
 0.62016995 0.66993756 0.49827586 0.48221985 0.41929895 0.35583072
 0.50707373 0.48513037 0.480555   0.56456106 0.00461463 0.54673641
 0.         0.50550605 0.490308   0.4661234  0.34134383 0.33753322
 0.34866335]
25
[-0.3192846  -0.38338103 -0.37833105 -0.39005993 -0.39452377 -0.38796618
 -0.37663591 -0.35201613 -0.49827586 -0.480856   -0.51749763 -0.55736381
 -0.50775071 -0.6165354  -0.72508863 -0.3128866  -0.00247836 -0.32287392
  0.         -0.73174532 -0.71307808 -0.72971685 -0.56221301 -0.55616642
 -0.56009565]
25
[(0.5718160402298855, -0.3192846011494254), (0.5494053195402298, -0.3833810333333334), (0.5305853965517247, -0.37833104597701134), (0.48819370919540184, -0.3900599321839079), (0.4459045057471262, -0.39452377241379344), (0.5694240379310346, -0.38796617816092), (0.6201699494252885, -0.3766359091954021), (0.6699375609195403, -0.3520161275862072), (0.4982758620689655, -0.4982758620689655), (0.482219851724137

In [6]:
# loop through the ArabesqueCoords List.
#Loop Through each sample and calculate the distance 
#d between: (samplex1,sampley1) and (meanx1,meanx2)
#save the distance vectors per sample
POSE = "Arabesque"
allDistanceVectors = []
for sample in ArabesqueCoords:
    xCoords = sample[0::3]
    #print(xCoords)
    yPos = sample[1::3]
    yCoords = [-y for y in yPos] # need to make it negative to be consistent - the mean skeleton's y saved the negative coords.
    SampleTuples = list(zip(xCoords, yCoords))
    #print(SampleTuples)
    longZip = list(zip(MeanTuples, SampleTuples))
    #print(longZip)
    distanceVector = []
    for ((x1,y1),(x2,y2)) in longZip:
        d = calcDistance(x1,y1,x2,y2)
        #print(d)
        distanceVector.append(d)
    allDistanceVectors.append(distanceVector)

print(allDistanceVectors)
print(len(allDistanceVectors))
print(len(allDistanceVectors[0]))
np.save("DataForSVM/"+POSE+"DistanceVectorsPerSample.npy", allDistanceVectors)
    


[[0.007909332832334698, 0.008044136116708752, 0.010805829319667894, 0.01176626272493377, 0.018399498472975194, 0.00606563056589456, 0.0091874681919777, 0.02201589333405364, 0.0024382992454708586, 0.029500582942674252, 0.1529537448789056, 0.2590009062920145, 0.010876538908769452, 0.15558473692809024, 0.29202337352318436, 0.01428002064068806, 0.005238042655335183, 0.01067953147551836, 0.0, 0.3423471522634619, 0.3069034539039228, 0.299097038434872, 0.2891342015008045, 0.29759522614773193, 0.2708693688443335], [0.010139359682326368, 0.014017009857804673, 0.0164231284592563, 0.017954218499897298, 0.02424382398035316, 0.008230022157542259, 0.013164633541065432, 0.024232281327365914, 0.0024382992454708586, 0.03948087118690687, 0.1549508678159346, 0.2626668039201561, 0.026469968528299206, 0.17136022241014479, 0.2987487141073836, 0.016295180313945303, 0.005238042655335183, 0.012783561556542688, 0.0, 0.3431803849322594, 0.3135340376817143, 0.30369006747781374, 0.2903948071006959, 0.2968896202510

In [18]:
#display(allDistanceVectors[0])
#plt.hist(allDistanceVectors[100])

In [7]:
#Save the X for arabesque...do for all the poses
#Build: [xyc,xyc] + [d1,d2,d3,d4,] [xyc....d1,d2,]
#TESTING basic version:
#testlist1 = [[1, 2, 3],[4,5,6]]
#testlist2 = [[10,20,30],[40,50,60]]
#resultList =[]
#for i in range(len(testlist1)):
#    resultList.append(testlist1[i]+testlist2[i])
#print(resultList)

#These features are mixing coordinates and distances: 100 features per sample: 75 + 25
ArabesqueAugFeaturesX = []
for i in range(len(ArabesqueCoords)):
    newList = list(ArabesqueCoords[i])+list(allDistanceVectors[i])
    ArabesqueAugFeaturesX.append(newList)
    
print(ArabesqueAugFeaturesX[0])
print(len(ArabesqueAugFeaturesX[0]))
np.save("DataForSVM/"+POSE+"AugMeanDistFeaturesX.npy", ArabesqueAugFeaturesX)

#For concatenating the different poses'data into one largeX:
#P1 = [[1,2,3,4],[5,6,7,8]]
#P2 = [[10,20,30],[11,22,33]]
#Res = P1+P2
#print(Res)

#Build the MassiveX with labels
#Run the data through an SVM
#Confusion Matrix
#Specificity
#Sensitivity
#Recall


[0.5796640000000001, 0.32026799999999994, 0.892814, 0.557149, 0.38555899999999993, 0.8373809999999999, 0.5408080000000001, 0.3748289999999999, 0.823098, 0.499919, 0.3910409999999999, 0.8667239999999999, 0.46324300000000007, 0.38836599999999993, 0.894381, 0.575477, 0.3883579999999999, 0.8091929999999999, 0.628653, 0.38016399999999995, 0.7940800000000001, 0.691891, 0.3503589999999999, 0.8887419999999999, 0.5, 0.5, 0.6499119999999999, 0.502013, 0.5027309999999999, 0.607399, 0.495953, 0.6498569999999999, 0.675133, 0.504014, 0.7697859999999999, 0.701661, 0.504012, 0.4973139999999999, 0.466601, 0.399832, 0.4864169999999999, 0.454518, 0.31610900000000003, 0.4837689999999999, 0.47866499999999995, 0.577451, 0.30674099999999993, 0.9179700000000001, 0.0, 0.0, 0.0, 0.557084, 0.3202319999999999, 0.844579, 0.0, 0.0, 0.0, 0.27530200000000005, 0.4783529999999999, 0.30574799999999996, 0.283364, 0.48644199999999993, 0.327499, 0.299819, 0.4811169999999999, 0.410191, 0.53069, 0.780723, 0.6843629999999999,

In [17]:
#display(ArabesqueAugFeaturesX[0][3:])
#plt.hist(ArabesqueAugFeaturesX[-97])