In [1]:
import numpy as np
import os
import cv2

In [7]:
PoseName = "Arabesque"
DIR = "D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/"+PoseName
POSES = ["Arabesque", "Demi-Plie", "Develope", "Penche", "Retire", "Second-Position", "Sus-sous", "Tendu"]
DANCERS = ["Dancer1","Dancer2","Dancer3","Dancer4","Dancer5","Dancer6","Dancer7","Dancer8","Dancer9","Dancer10","Dancer11",
          "Dancer12","Dancer13","Dancer14","Dancer15","Dancer16","Dancer17","Dancer18","Dancer19","Dancer20","Dancer21","Dancer22","Dancer23","Dancer25",
          "Dancer26","Dancer27","Dancer28","Dancer29","Dancer30",]

X=[]
y=[]

def generateSaveHOGData():
    global dancerNum
    class_num = POSES.index()
    for dancer in DANCERS:
        dancerpath = DIR + "/" + dancer
        print(dancerpath)
        for file in os.listdir(dancerpath):
           if file.endswith('.jpg'):
                file_path = dancerpath+"/"+file
                print(file)
                im = cv2.imread(file_path,cv2.IMREAD_GRAYSCALE)
                #print(im)
                #Extract HOG features from each image, append to X and y
                h = hog.compute(im) #2D array
                h_flattened = h.flatten() # flatten it to 1D array
                X.append(h_flattened)
                y.append(class_num)
generateSaveHOGData()

print(len(X))

D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer1
09-14-45_1_snapshot.jpg
[[114 114 114 ... 114 111 110]
 [115 115 114 ... 114 113 111]
 [117 116 115 ... 116 115 114]
 ...
 [127 127 128 ... 120 119 118]
 [126 126 127 ... 119 118 117]
 [126 126 127 ... 118 118 117]]
09-14-46_2_snapshot.jpg
[[112 112 112 ... 111 111 112]
 [110 111 112 ... 113 112 114]
 [114 114 115 ... 114 114 116]
 ...
 [128 128 128 ... 118 117 116]
 [128 128 127 ... 119 117 116]
 [128 128 127 ... 119 118 117]]
09-14-47_3_snapshot.jpg
[[109 109 110 ... 115 115 115]
 [111 111 111 ... 115 116 116]
 [114 113 114 ... 116 116 117]
 ...
 [128 128 128 ... 117 117 118]
 [127 127 127 ... 117 117 118]
 [127 127 127 ... 117 117 119]]
09-14-49_4_snapshot.jpg
[[109 111 113 ... 115 115 116]
 [112 113 114 ... 115 115 116]
 [116 115 115 ... 116 116 116]
 ...
 [130 130 129 ... 116 117 117]
 [129 129 128 ... 117 118 119]
 [128 128 128 ... 118 120 122]]
09-14-50_5_snap

 [123 124 125 ... 119 120 120]]
12-38-39_2_snapshot.jpg
[[ 94  95  96 ... 100 100 100]
 [ 96  97  98 ... 100 100  99]
 [ 99 100 100 ... 101 100  99]
 ...
 [126 125 125 ... 116 115 115]
 [125 126 125 ... 115 115 116]
 [125 126 126 ... 115 116 117]]
12-38-40_3_snapshot.jpg
[[ 99  99  99 ... 100 100  99]
 [100 100 100 ... 101 101 101]
 [102 102 101 ... 102 102 102]
 ...
 [122 124 125 ... 118 116 115]
 [122 123 124 ... 118 116 114]
 [121 122 124 ... 118 116 114]]
12-38-41_4_snapshot.jpg
[[ 99  99 100 ...  97  97  98]
 [100 101 101 ...  98  98  99]
 [101 101 102 ...  99  98 100]
 ...
 [122 122 123 ... 117 116 116]
 [122 122 123 ... 116 116 116]
 [122 122 123 ... 116 116 116]]
12-38-42_5_snapshot.jpg
[[ 97  98 100 ... 100  99  98]
 [ 99 100 101 ... 100  99  98]
 [102 102 102 ... 101 100  99]
 ...
 [124 123 124 ... 115 115 117]
 [122 122 122 ... 116 116 117]
 [122 121 121 ... 117 117 118]]
12-38-43_6_snapshot.jpg
[[102 100  98 ...  99  97  95]
 [101 100 100 ... 101  99  97]
 [101 101 102 ... 

 [125 123 123 ... 118 116 114]]
09-22-05_2_snapshot.jpg
[[104 105 106 ...  88  88  88]
 [106 106 107 ...  89  89  89]
 [108 108 108 ...  90  90  90]
 ...
 [125 125 126 ... 118 117 116]
 [125 125 125 ... 118 117 117]
 [124 125 125 ... 117 117 117]]
09-22-06_3_snapshot.jpg
[[107 106 105 ...  88  88  88]
 [108 107 106 ...  89  89  89]
 [110 109 108 ...  91  90  90]
 ...
 [122 123 124 ... 118 117 115]
 [124 124 125 ... 119 117 115]
 [126 126 127 ... 119 117 115]]
09-22-07_4_snapshot.jpg
[[104 104 104 ...  88  86  85]
 [104 104 105 ...  89  88  87]
 [105 105 106 ...  91  90  89]
 ...
 [124 124 125 ... 119 118 118]
 [124 124 125 ... 118 117 117]
 [125 125 124 ... 117 116 115]]
09-22-08_5_snapshot.jpg
[[103 105 106 ...  87  86  86]
 [105 106 107 ...  88  87  87]
 [107 108 108 ...  89  88  88]
 ...
 [126 126 126 ... 116 115 115]
 [126 125 125 ... 115 114 115]
 [125 125 124 ... 114 113 114]]
09-22-09_6_snapshot.jpg
[[103 105 106 ...  89  87  86]
 [103 105 106 ...  89  87  86]
 [104 106 107 ... 

[[ 82  82  83 ...  80  80  79]
 [ 82  83  83 ...  81  81  81]
 [ 84  84  84 ...  83  82  82]
 ...
 [127 130 131 ... 116 116 116]
 [125 128 129 ... 116 116 116]
 [124 127 128 ... 117 117 117]]
09-06-33_5_snapshot.jpg
[[ 83  83  83 ...  80  80  80]
 [ 83  84  84 ...  82  81  81]
 [ 84  85  85 ...  83  83  83]
 ...
 [126 128 130 ... 117 116 116]
 [127 129 130 ... 116 116 116]
 [128 130 131 ... 116 116 116]]
09-06-34_6_snapshot.jpg
[[ 82  82  83 ...  79  79  79]
 [ 82  82  84 ...  81  81  81]
 [ 83  83  85 ...  83  83  83]
 ...
 [128 128 129 ... 117 116 117]
 [128 128 128 ... 116 115 116]
 [128 128 128 ... 115 115 116]]
09-06-35_7_snapshot.jpg
[[ 82  82  83 ...  80  80  80]
 [ 82  83  84 ...  82  81  81]
 [ 84  84  86 ...  84  83  82]
 ...
 [128 128 129 ... 116 116 116]
 [128 129 129 ... 117 116 115]
 [129 129 130 ... 117 115 114]]
09-06-36_8_snapshot.jpg
[[ 83  83  83 ...  81  80  80]
 [ 84  83  83 ...  81  80  79]
 [ 84  84  84 ...  82  80  80]
 ...
 [126 129 132 ... 117 117 118]
 [126 1

12-27-51_6_snapshot.jpg
[[112 111 110 ... 104 104 105]
 [113 112 112 ... 105 104 104]
 [114 113 113 ... 106 104 103]
 ...
 [129 129 128 ... 124 124 122]
 [129 128 128 ... 123 123 121]
 [130 128 128 ... 123 122 119]]
12-27-52_7_snapshot.jpg
[[110 109 109 ... 102 102 102]
 [110 110 110 ... 105 104 103]
 [111 112 113 ... 107 106 105]
 ...
 [129 129 131 ... 125 124 123]
 [130 130 131 ... 124 124 124]
 [131 131 131 ... 124 124 124]]
12-27-53_8_snapshot.jpg
[[113 112 111 ... 103 104 105]
 [114 113 112 ... 104 104 104]
 [115 114 114 ... 104 104 103]
 ...
 [127 127 128 ... 123 123 123]
 [128 127 127 ... 122 122 122]
 [129 127 126 ... 122 121 121]]
12-27-54_9_snapshot.jpg
[[112 112 111 ... 103 102 101]
 [112 112 112 ... 103 103 102]
 [113 113 112 ... 105 104 104]
 ...
 [129 129 131 ... 124 125 126]
 [128 128 129 ... 123 124 124]
 [126 126 126 ... 123 123 123]]
12-27-55_10_snapshot.jpg
[[111 112 109 ... 104 105 107]
 [114 115 113 ... 103 103 105]
 [116 117 115 ... 104 103 105]
 ...
 [132 129 128

 [123 123 123 ...  96  96  95]]
09-19-39_9_snapshot.jpg
[[108 108 108 ...  88  87  87]
 [108 108 108 ...  87  86  86]
 [108 108 108 ...  87  87  87]
 ...
 [122 123 124 ...  97  96  95]
 [122 123 124 ...  97  96  95]
 [122 123 125 ...  97  95  94]]
09-19-40_10_snapshot.jpg
[[110 110 109 ...  87  87  87]
 [110 110 109 ...  88  87  87]
 [110 110 110 ...  88  87  87]
 ...
 [122 123 124 ...  97  97  98]
 [122 123 124 ...  97  97  97]
 [122 123 124 ...  96  96  96]]
09-19-58_1_snapshot.jpg
[[103 104 105 ...  85  84  83]
 [105 106 106 ...  85  84  83]
 [106 107 108 ...  86  85  84]
 ...
 [120 121 122 ...  96  96  97]
 [117 118 120 ...  96  96  97]
 [115 116 119 ...  97  97  97]]
09-19-59_2_snapshot.jpg
[[104 105 106 ...  82  81  82]
 [104 105 106 ...  82  81  82]
 [104 105 107 ...  83  82  83]
 ...
 [121 122 123 ...  98  97  96]
 [121 121 122 ...  97  96  95]
 [121 121 122 ...  97  96  94]]
09-20-00_3_snapshot.jpg
[[102 104 104 ...  85  83  83]
 [103 105 106 ...  85  84  83]
 [104 106 107 ...

 [122 124 127 ... 119 118 117]]
12-22-38_2_snapshot.jpg
[[110 108 106 ... 100  99  98]
 [113 111 109 ... 101 100  99]
 [113 111 109 ... 102 101 100]
 ...
 [126 125 125 ... 119 117 115]
 [126 125 125 ... 119 117 116]
 [126 125 125 ... 121 119 118]]
12-22-39_3_snapshot.jpg
[[110 109 107 ... 100  98  98]
 [110 109 109 ... 101  99  97]
 [110 110 110 ... 103 100  97]
 ...
 [125 124 124 ... 117 118 119]
 [126 126 127 ... 118 119 119]
 [126 128 129 ... 121 120 119]]
12-22-40_4_snapshot.jpg
[[108 107 107 ... 102 103 102]
 [109 109 108 ... 102 102 102]
 [110 110 110 ... 103 102 101]
 ...
 [122 123 123 ... 120 119 118]
 [123 124 125 ... 120 118 116]
 [123 125 126 ... 119 117 116]]
12-22-41_5_snapshot.jpg
[[108 107 106 ... 101  99  98]
 [110 109 108 ... 101 101 100]
 [111 110 109 ... 102 102 102]
 ...
 [123 125 126 ... 118 117 116]
 [124 125 125 ... 118 117 117]
 [125 125 124 ... 120 120 121]]
12-22-42_6_snapshot.jpg
[[103 106 109 ...  98  99 100]
 [104 107 108 ...  99 100 100]
 [108 109 109 ... 

 [122 124 125 ... 122 121 120]]
09-13-04_2_snapshot.jpg
[[103 102 103 ... 105 105 103]
 [104 103 104 ... 105 106 105]
 [105 104 105 ... 105 107 107]
 ...
 [126 125 126 ... 122 121 120]
 [127 125 125 ... 123 122 121]
 [127 125 124 ... 124 123 122]]
09-13-05_3_snapshot.jpg
[[101 103 102 ... 102 102 103]
 [103 105 105 ... 102 102 102]
 [103 105 105 ... 102 102 102]
 ...
 [125 126 127 ... 123 123 122]
 [124 125 127 ... 123 123 123]
 [124 125 126 ... 122 123 123]]
09-13-06_4_snapshot.jpg
[[100 101 102 ... 103 104 104]
 [101 102 103 ... 105 104 103]
 [102 103 104 ... 106 104 102]
 ...
 [125 125 125 ... 121 121 122]
 [125 125 125 ... 121 121 122]
 [125 126 126 ... 120 120 121]]
09-13-07_5_snapshot.jpg
[[103 101 102 ... 101 102 105]
 [104 103 103 ... 102 103 104]
 [105 104 104 ... 105 105 105]
 ...
 [125 125 126 ... 122 122 121]
 [126 126 126 ... 122 122 122]
 [127 126 126 ... 121 121 121]]
09-13-09_6_snapshot.jpg
[[101 101 102 ... 107 106 105]
 [102 102 103 ... 107 105 104]
 [103 104 105 ... 

 [124 124 125 ... 120 120 121]]
09-24-36_5_snapshot.jpg
[[101 101 102 ... 104 103 103]
 [103 103 103 ... 105 104 103]
 [104 104 105 ... 106 104 103]
 ...
 [125 127 130 ... 122 121 120]
 [126 126 127 ... 122 121 121]
 [127 125 124 ... 121 121 121]]
09-24-37_6_snapshot.jpg
[[104 105 105 ... 102 104 107]
 [104 104 105 ... 104 104 105]
 [105 105 105 ... 105 105 104]
 ...
 [127 128 129 ... 122 122 122]
 [127 129 130 ... 122 122 122]
 [128 130 131 ... 122 121 121]]
09-24-38_7_snapshot.jpg
[[101 102 103 ... 105 105 105]
 [103 104 104 ... 104 104 104]
 [105 105 105 ... 105 105 106]
 ...
 [126 126 126 ... 122 121 120]
 [126 126 127 ... 121 120 119]
 [125 126 127 ... 119 119 118]]
09-24-39_8_snapshot.jpg
[[101 102 103 ... 102 100 101]
 [103 103 104 ... 102 102 103]
 [104 105 105 ... 102 104 105]
 ...
 [124 125 128 ... 121 121 120]
 [125 126 128 ... 122 122 120]
 [127 127 129 ... 123 122 121]]
09-24-40_9_snapshot.jpg
[[105 103 101 ... 105 105 107]
 [107 105 104 ... 104 105 106]
 [106 106 105 ... 

[[108 109 109 ... 102 102 103]
 [109 110 109 ... 102 102 103]
 [111 110 108 ... 102 103 103]
 ...
 [124 125 126 ... 120 122 125]
 [123 124 125 ... 120 121 124]
 [123 124 125 ... 122 122 124]]
09-19-37_9_snapshot.jpg
[[108 107 107 ... 102 101  99]
 [108 107 107 ... 101 101  99]
 [108 107 107 ... 101 101 100]
 ...
 [124 124 125 ... 124 123 123]
 [127 127 127 ... 123 123 124]
 [127 127 126 ... 122 123 125]]
09-19-38_10_snapshot.jpg
[[106 107 107 ...  99 100 103]
 [105 105 106 ... 100 100 102]
 [104 105 106 ... 101 101 102]
 ...
 [124 126 128 ... 124 123 122]
 [123 125 126 ... 124 123 122]
 [122 123 125 ... 123 123 122]]
09-19-51_1_snapshot.jpg
[[106 105 106 ... 100  99  99]
 [106 106 107 ... 101 100  99]
 [107 107 109 ... 101 100  99]
 ...
 [124 124 125 ... 121 120 120]
 [125 124 124 ... 121 120 119]
 [127 126 125 ... 121 119 119]]
09-19-52_2_snapshot.jpg
[[107 107 107 ...  98  97  98]
 [106 107 107 ...  99  99 100]
 [106 106 107 ... 101 101 102]
 ...
 [125 126 127 ... 122 121 120]
 [124 

 [128 127 127 ... 124 123 124]]
09-17-44_10_snapshot.jpg
[[106 106 107 ...  97  96  95]
 [108 107 108 ...  98  98  97]
 [111 110 109 ...  99  99 100]
 ...
 [126 129 130 ... 123 124 125]
 [128 129 129 ... 123 124 126]
 [130 129 128 ... 124 125 127]]
09-17-55_1_snapshot.jpg
[[110 110 109 ...  95  95  97]
 [110 110 110 ...  97  97  98]
 [110 111 112 ...  99 100 101]
 ...
 [126 128 131 ... 125 123 121]
 [127 128 130 ... 123 122 120]
 [127 127 129 ... 123 122 121]]
09-17-56_2_snapshot.jpg
[[107 108 108 ... 101 100  98]
 [108 109 109 ... 102 101 100]
 [110 110 110 ... 101 100  98]
 ...
 [129 129 125 ... 126 125 124]
 [130 130 126 ... 126 125 123]
 [131 130 125 ... 125 125 123]]
09-17-57_3_snapshot.jpg
[[106 108 109 ...  98  98 101]
 [106 108 110 ...  96  96  99]
 [107 109 111 ...  95  95  97]
 ...
 [129 129 130 ... 123 121 121]
 [129 129 130 ... 123 122 122]
 [129 129 129 ... 125 124 124]]
09-17-58_4_snapshot.jpg
[[107 109 109 ...  97  96  96]
 [107 109 109 ...  98  97  97]
 [109 110 110 ...

 [125 126 126 ... 124 120 117]]
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer20
12-37-41_1_snapshot.jpg
[[108 109 109 ... 101  99  98]
 [108 109 110 ... 101 100 100]
 [108 110 111 ... 102 102 103]
 ...
 [123 124 126 ... 120 120 120]
 [122 123 125 ... 120 120 119]
 [121 122 124 ... 122 121 120]]
12-37-42_2_snapshot.jpg
[[106 107 107 ... 101  99 100]
 [107 107 108 ... 101 100 100]
 [108 108 108 ... 101 101 101]
 ...
 [121 121 123 ... 121 121 122]
 [122 123 124 ... 122 122 124]
 [125 125 125 ... 121 122 124]]
12-37-43_3_snapshot.jpg
[[106 109 112 ... 101 102 102]
 [107 109 111 ... 102 102 102]
 [108 109 109 ... 102 102 102]
 ...
 [124 124 126 ... 122 120 118]
 [124 123 124 ... 122 121 119]
 [125 123 123 ... 122 122 120]]
12-37-44_4_snapshot.jpg
[[107 106 105 ... 100 100 101]
 [107 106 105 ... 100 100 101]
 [108 107 106 ... 100 100 101]
 ...
 [124 125 126 ... 120 120 120]
 [124 125 126 ... 120 119 119]
 [124 125 126 

12-25-42_1_snapshot.jpg
[[116 115 117 ... 105 105 106]
 [117 117 118 ... 105 105 105]
 [119 118 119 ... 107 105 104]
 ...
 [129 129 129 ... 122 122 122]
 [127 128 128 ... 121 122 122]
 [125 126 128 ... 121 122 123]]
12-25-43_2_snapshot.jpg
[[116 116 115 ... 105 104 103]
 [117 116 116 ... 106 105 104]
 [118 118 117 ... 108 107 106]
 ...
 [128 128 128 ... 121 121 123]
 [127 127 127 ... 120 121 123]
 [126 126 126 ... 120 121 124]]
12-25-44_3_snapshot.jpg
[[114 114 114 ... 108 106 105]
 [116 116 116 ... 108 107 106]
 [118 118 118 ... 108 108 108]
 ...
 [127 127 129 ... 122 122 122]
 [127 127 128 ... 122 122 122]
 [129 128 128 ... 122 122 122]]
12-25-45_4_snapshot.jpg
[[114 116 117 ... 106 105 105]
 [116 117 118 ... 106 106 105]
 [118 119 119 ... 108 107 107]
 ...
 [127 127 127 ... 122 121 122]
 [126 126 127 ... 121 121 123]
 [126 126 127 ... 120 121 124]]
12-25-47_5_snapshot.jpg
[[114 115 115 ... 107 107 107]
 [114 114 115 ... 107 107 106]
 [115 115 116 ... 107 107 106]
 ...
 [129 130 130 

[[ 88  88  89 ...  95  95  95]
 [ 88  87  88 ...  95  94  94]
 [ 88  88  89 ...  95  95  94]
 ...
 [126 128 128 ... 121 119 118]
 [127 129 129 ... 121 120 118]
 [126 128 128 ... 122 121 120]]
12-32-05_5_snapshot.jpg
[[ 84  89  94 ...  92  91  91]
 [ 86  89  93 ...  93  93  92]
 [ 88  90  92 ...  95  94  94]
 ...
 [129 129 130 ... 123 122 121]
 [128 128 129 ... 121 121 122]
 [127 128 128 ... 120 121 122]]
12-32-07_6_snapshot.jpg
[[ 88  88  89 ...  92  91  90]
 [ 89  89  90 ...  93  92  92]
 [ 91  91  91 ...  95  94  94]
 ...
 [124 126 128 ... 120 119 119]
 [127 128 130 ... 118 117 117]
 [128 129 130 ... 116 116 116]]
12-32-08_7_snapshot.jpg
[[ 89  88  88 ...  92  91  91]
 [ 89  88  88 ...  92  92  92]
 [ 92  90  89 ...  94  94  94]
 ...
 [130 128 127 ... 122 121 120]
 [129 128 126 ... 120 120 120]
 [129 127 125 ... 119 120 120]]
12-32-09_8_snapshot.jpg
[[ 88  89  89 ...  91  90  90]
 [ 88  89  89 ...  92  91  91]
 [ 89  90  90 ...  93  92  92]
 ...
 [127 127 127 ... 120 119 120]
 [124 1

09-23-53_5_snapshot.jpg
[[100  99 100 ... 104 102 102]
 [101 100 101 ... 104 102 103]
 [103 102 103 ... 105 103 103]
 ...
 [124 124 125 ... 120 119 118]
 [125 124 124 ... 119 119 119]
 [125 123 123 ... 118 119 119]]
09-23-54_6_snapshot.jpg
[[101 101 101 ... 101 101 101]
 [101 101 102 ... 102 102 102]
 [101 102 103 ... 104 104 103]
 ...
 [124 124 124 ... 119 119 119]
 [124 124 123 ... 118 118 118]
 [124 123 122 ... 119 119 119]]
09-23-55_7_snapshot.jpg
[[ 99 100 102 ... 102 103 104]
 [100 101 103 ... 103 104 104]
 [102 103 104 ... 104 104 104]
 ...
 [124 124 125 ... 122 121 121]
 [125 125 125 ... 120 119 120]
 [125 125 125 ... 117 117 117]]
09-23-56_8_snapshot.jpg
[[101 102 102 ... 101 102 103]
 [100 101 102 ... 102 103 103]
 [100 101 103 ... 103 103 103]
 ...
 [123 123 123 ... 119 119 118]
 [122 123 123 ... 119 118 117]
 [122 123 123 ... 119 118 117]]
09-23-58_9_snapshot.jpg
[[100 102 103 ... 102 102 102]
 [100 102 103 ... 103 103 103]
 [101 103 103 ... 104 105 105]
 ...
 [124 124 124 

 [122 122 122 ... 120 120 121]]
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer28
09-14-35_1_snapshot.jpg
[[107 107 107 ... 102 103 104]
 [107 108 107 ... 104 103 102]
 [108 108 109 ... 105 103 101]
 ...
 [125 126 127 ... 123 122 121]
 [124 125 127 ... 121 121 120]
 [123 124 126 ... 120 120 119]]
09-14-36_2_snapshot.jpg
[[106 107 108 ... 104 103 104]
 [106 107 108 ... 103 102 103]
 [107 108 109 ... 103 102 102]
 ...
 [128 127 126 ... 123 123 122]
 [127 127 127 ... 124 123 121]
 [126 127 127 ... 125 123 121]]
09-14-38_3_snapshot.jpg
[[107 104 104 ... 104 104 105]
 [109 107 106 ... 103 103 103]
 [109 107 107 ... 102 102 102]
 ...
 [125 125 125 ... 120 120 122]
 [125 125 125 ... 120 120 122]
 [126 125 125 ... 120 120 123]]
09-14-39_4_snapshot.jpg
[[106 106 106 ... 105 106 107]
 [108 108 108 ... 106 106 106]
 [111 110 109 ... 106 106 106]
 ...
 [124 124 125 ... 123 123 124]
 [123 123 124 ... 123 123 123]
 [123 123 123 

 [123 124 125 ... 122 122 123]]
09-28-54_10_snapshot.jpg
[[108 108 108 ... 106 105 105]
 [111 111 111 ... 106 106 106]
 [112 111 110 ... 106 106 107]
 ...
 [125 126 128 ... 125 124 123]
 [125 125 126 ... 123 123 122]
 [126 125 124 ... 122 121 121]]
09-29-10_1_snapshot.jpg
[[106 108 110 ... 103 105 103]
 [108 109 110 ... 104 106 104]
 [110 110 109 ... 106 107 104]
 ...
 [125 125 126 ... 122 120 119]
 [123 124 126 ... 122 121 120]
 [121 123 126 ... 123 122 122]]
09-29-11_2_snapshot.jpg
[[105 107 107 ... 105 106 107]
 [107 108 108 ... 104 104 106]
 [109 110 110 ... 103 104 105]
 ...
 [123 124 124 ... 123 123 123]
 [122 122 122 ... 125 123 121]
 [122 122 122 ... 126 122 119]]
09-29-12_3_snapshot.jpg
[[107 107 107 ... 106 106 106]
 [108 108 108 ... 106 106 105]
 [109 110 110 ... 108 106 105]
 ...
 [124 124 125 ... 125 123 122]
 [125 124 125 ... 125 123 123]
 [126 125 126 ... 122 120 120]]
09-29-13_4_snapshot.jpg
[[104 104 106 ... 107 107 107]
 [106 106 107 ... 106 106 107]
 [108 108 108 ...

In [ ]:
BASE_DIR = "D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer"
POSES = ["Arabesque", "Demi-Plie", "Develope", "Penche", "Retire", "Second-Position", "Sus-sous", "Tendu"]
DANCERS = ["Dancer1","Dancer2","Dancer3","Dancer4","Dancer5","Dancer6","Dancer7","Dancer8","Dancer9","Dancer10","Dancer11",
          "Dancer12","Dancer13","Dancer14","Dancer15","Dancer16","Dancer17","Dancer18","Dancer19","Dancer20","Dancer21","Dancer22","Dancer23","Dancer25",
          "Dancer26","Dancer27","Dancer28","Dancer29","Dancer30",]

X=[]
y=[]

hog = cv2.HOGDescriptor()

def createHOGData():
    for pose in POSES:
        print(pose)
        path = BASE_DIR +"/"+pose #os.path.join(BASE_DIR, pose) # path to each pose folder
        class_num = POSES.index(pose) # numerical value for each class
        for dancer in DANCERS:
            dancerpath = path +"/" + dancer
            print(dancerpath)
            for file in os.listdir(dancerpath):
                print(file)
                if file.endswith('.jpg'):
                    file_path = dancerpath+"/"+file #os.path.join(dancerpath,file)
                    print(file_path)
                    im = cv2.imread(file_path, cv2.IMREAD_GRAYSCALE)
                    print(im)
                    #Extract HOG features from each image, append to X and y
                    h = hog.compute(im) #2D array
                    h_flattened = h.flatten() # flatten it to 1D array
                    X.append(h_flattened)
                    y.append(class_num)
                
createHOGData()



Arabesque
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer1
09-14-45_1_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer1/09-14-45_1_snapshot.jpg
[[114 114 114 ... 114 111 110]
 [115 115 114 ... 114 113 111]
 [117 116 115 ... 116 115 114]
 ...
 [127 127 128 ... 120 119 118]
 [126 126 127 ... 119 118 117]
 [126 126 127 ... 118 118 117]]
09-14-45_1_snapshot_keypoints.json
09-14-45_1_snapshot_rendered.png
09-14-46_2_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer1/09-14-46_2_snapshot.jpg
[[112 112 112 ... 111 111 112]
 [110 111 112 ... 113 112 114]
 [114 114 115 ... 114 114 116]
 ...
 [128 128 128 ... 118 117 116]
 [128 128 127 ... 119 117 116]
 [128 128 127 ... 119 118 117]]
09-14-46_2_snapshot_keypoints.json
09-14-46_2_snapshot_rendered.png
09-14-47_3_

09-15-25_9_snapshot_keypoints.json
09-15-25_9_snapshot_rendered.png
09-15-26_10_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer1/09-15-26_10_snapshot.jpg
[[110 111 111 ... 116 114 112]
 [113 113 113 ... 114 114 112]
 [115 115 115 ... 116 116 115]
 ...
 [127 128 128 ... 118 117 117]
 [128 128 127 ... 117 117 117]
 [128 128 127 ... 117 116 116]]
09-15-26_10_snapshot_keypoints.json
09-15-26_10_snapshot_rendered.png
09-15-52_1_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer1/09-15-52_1_snapshot.jpg
[[110 110 111 ... 111 111 110]
 [111 111 111 ... 111 111 111]
 [113 113 112 ... 112 112 112]
 ...
 [126 128 130 ... 118 116 115]
 [125 127 128 ... 117 117 117]
 [126 128 129 ... 117 117 118]]
09-15-52_1_snapshot_keypoints.json
09-15-52_1_snapshot_rendered.png
09-15-53_2_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-w

12-37-19_9_snapshot_keypoints.json
12-37-19_9_snapshot_rendered.png
12-37-20_10_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer2/12-37-20_10_snapshot.jpg
[[ 99 100 100 ... 102 102 101]
 [100 100 101 ... 103 102 102]
 [101 102 103 ... 103 103 103]
 ...
 [126 126 126 ... 119 119 118]
 [127 127 127 ... 119 118 117]
 [128 128 128 ... 119 118 117]]
12-37-20_10_snapshot_keypoints.json
12-37-20_10_snapshot_rendered.png
12-37-48_1_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer2/12-37-48_1_snapshot.jpg
[[102 103 103 ... 102 102 102]
 [104 104 104 ... 102 102 103]
 [105 105 105 ... 103 103 103]
 ...
 [127 127 127 ... 120 120 120]
 [126 126 127 ... 120 119 119]
 [125 125 126 ... 120 119 119]]
12-37-48_1_snapshot_keypoints.json
12-37-48_1_snapshot_rendered.png
12-37-49_2_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-w

09-15-11_1_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer3/09-15-11_1_snapshot.jpg
[[ 75  77  78 ...  76  77  77]
 [ 76  77  78 ...  77  77  77]
 [ 77  78  79 ...  78  78  78]
 ...
 [130 131 132 ... 125 125 124]
 [129 130 132 ... 125 126 125]
 [128 129 131 ... 126 126 125]]
09-15-11_1_snapshot_keypoints.json
09-15-11_1_snapshot_rendered.png
09-15-12_2_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer3/09-15-12_2_snapshot.jpg
[[ 76  76  76 ...  75  74  74]
 [ 76  76  76 ...  76  75  75]
 [ 77  77  77 ...  77  76  76]
 ...
 [131 133 134 ... 124 123 122]
 [132 134 134 ... 124 123 122]
 [133 135 135 ... 123 123 122]]
09-15-12_2_snapshot_keypoints.json
09-15-12_2_snapshot_rendered.png
09-15-13_3_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dance

09-17-11_1_snapshot_keypoints.json
09-17-11_1_snapshot_rendered.png
09-17-12_2_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer3/09-17-12_2_snapshot.jpg
[[ 77  77  77 ...  78  78  79]
 [ 77  77  77 ...  79  79  79]
 [ 77  77  78 ...  79  79  79]
 ...
 [131 132 134 ... 124 123 122]
 [132 133 134 ... 124 123 122]
 [134 134 134 ... 125 124 123]]
09-17-12_2_snapshot_keypoints.json
09-17-12_2_snapshot_rendered.png
09-17-13_3_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer3/09-17-13_3_snapshot.jpg
[[ 78  77  77 ...  75  74  74]
 [ 76  76  76 ...  76  76  76]
 [ 75  75  76 ...  77  77  77]
 ...
 [134 134 134 ... 124 123 124]
 [133 133 134 ... 125 124 125]
 [133 133 134 ... 125 125 126]]
09-17-13_3_snapshot_keypoints.json
09-17-13_3_snapshot_rendered.png
09-17-14_4_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64

09-22-05_2_snapshot_keypoints.json
09-22-05_2_snapshot_rendered.png
09-22-06_3_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer4/09-22-06_3_snapshot.jpg
[[107 106 105 ...  88  88  88]
 [108 107 106 ...  89  89  89]
 [110 109 108 ...  91  90  90]
 ...
 [122 123 124 ... 118 117 115]
 [124 124 125 ... 119 117 115]
 [126 126 127 ... 119 117 115]]
09-22-06_3_snapshot_keypoints.json
09-22-06_3_snapshot_rendered.png
09-22-07_4_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer4/09-22-07_4_snapshot.jpg
[[104 104 104 ...  88  86  85]
 [104 104 105 ...  89  88  87]
 [105 105 106 ...  91  90  89]
 ...
 [124 124 125 ... 119 118 118]
 [124 124 125 ... 118 117 117]
 [125 125 124 ... 117 116 115]]
09-22-07_4_snapshot_keypoints.json
09-22-07_4_snapshot_rendered.png
09-22-08_5_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64

12-31-29_1_snapshot_keypoints.json
12-31-29_1_snapshot_rendered.png
12-31-30_2_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer5/12-31-30_2_snapshot.jpg
[[113 114 113 ...  97  98  99]
 [114 115 114 ...  98  99  99]
 [116 116 115 ... 100 100 100]
 ...
 [125 124 124 ... 116 117 118]
 [123 123 124 ... 116 117 118]
 [124 124 124 ... 116 117 118]]
12-31-30_2_snapshot_keypoints.json
12-31-30_2_snapshot_rendered.png
12-31-31_3_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer5/12-31-31_3_snapshot.jpg
[[110 109 110 ...  98  97  97]
 [110 110 111 ... 100 100  99]
 [112 112 113 ... 101 101 101]
 ...
 [126 125 126 ... 118 118 117]
 [126 125 126 ... 118 117 116]
 [126 125 126 ... 117 117 116]]
12-31-31_3_snapshot_keypoints.json
12-31-31_3_snapshot_rendered.png
12-31-32_4_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64

12-32-19_1_snapshot_keypoints.json
12-32-19_1_snapshot_rendered.png
12-32-20_2_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer5/12-32-20_2_snapshot.jpg
[[114 111 110 ... 100  98  97]
 [115 113 112 ... 102 101 100]
 [117 115 114 ... 104 104 103]
 ...
 [127 127 127 ... 117 117 117]
 [126 126 126 ... 117 117 117]
 [125 125 126 ... 117 117 116]]
12-32-20_2_snapshot_keypoints.json
12-32-20_2_snapshot_rendered.png
12-32-21_3_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer5/12-32-21_3_snapshot.jpg
[[108 111 114 ...  97 100 103]
 [111 113 115 ...  98  99 101]
 [115 115 116 ... 100  99  99]
 ...
 [126 126 127 ... 119 118 117]
 [125 125 126 ... 119 118 117]
 [124 124 124 ... 119 118 117]]
12-32-21_3_snapshot_keypoints.json
12-32-21_3_snapshot_rendered.png
12-32-22_4_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64

09-06-39_10_snapshot_keypoints.json
09-06-39_10_snapshot_rendered.png
09-07-06_1_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer6/09-07-06_1_snapshot.jpg
[[ 83  83  82 ...  79  80  80]
 [ 82  82  83 ...  80  80  81]
 [ 82  82  83 ...  82  81  81]
 ...
 [129 129 130 ... 115 115 116]
 [129 129 129 ... 115 115 116]
 [127 128 128 ... 114 114 116]]
09-07-06_1_snapshot_keypoints.json
09-07-06_1_snapshot_rendered.png
09-07-07_2_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer6/09-07-07_2_snapshot.jpg
[[ 81  82  83 ...  80  79  78]
 [ 84  84  84 ...  81  80  79]
 [ 88  87  86 ...  82  81  81]
 ...
 [128 128 128 ... 116 116 116]
 [129 129 128 ... 116 116 117]
 [131 130 129 ... 116 116 117]]
09-07-07_2_snapshot_keypoints.json
09-07-07_2_snapshot_rendered.png
09-07-08_3_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win

09-08-11_10_snapshot_keypoints.json
09-08-11_10_snapshot_rendered.png
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer7
12-26-29_1_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer7/12-26-29_1_snapshot.jpg
[[108 108 109 ... 104 103 103]
 [109 109 110 ... 104 103 103]
 [110 110 111 ... 104 104 103]
 ...
 [128 127 127 ... 126 125 123]
 [129 127 126 ... 125 123 121]
 [131 128 126 ... 124 121 119]]
12-26-29_1_snapshot_keypoints.json
12-26-29_1_snapshot_rendered.png
12-26-30_2_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer7/12-26-30_2_snapshot.jpg
[[110 110 111 ... 105 104 104]
 [110 110 111 ... 105 105 105]
 [111 111 112 ... 106 106 106]
 ...
 [129 129 128 ... 126 126 127]
 [128 129 129 ... 125 125 124]
 [125 126 128 ... 127 126 124]]
12-26-30_2_snapshot

12-27-12_9_snapshot_keypoints.json
12-27-12_9_snapshot_rendered.png
12-27-13_10_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer7/12-27-13_10_snapshot.jpg
[[108 108 109 ... 101 100 100]
 [110 110 111 ... 102 101 101]
 [111 111 111 ... 104 103 103]
 ...
 [128 129 130 ... 124 125 125]
 [128 129 130 ... 125 124 124]
 [129 130 130 ... 125 124 123]]
12-27-13_10_snapshot_keypoints.json
12-27-13_10_snapshot_rendered.png
12-27-45_1_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended/DatasetPosePerDancer/Arabesque/Dancer7/12-27-45_1_snapshot.jpg
[[110 110 110 ... 106 105 105]
 [111 111 111 ... 105 105 105]
 [113 113 113 ... 105 105 104]
 ...
 [128 129 131 ... 123 122 121]
 [127 128 131 ... 123 122 121]
 [126 127 130 ... 123 122 121]]
12-27-45_1_snapshot_keypoints.json
12-27-45_1_snapshot_rendered.png
12-27-46_2_snapshot.jpg
D:/OpenPose-DataRuns/openpose-1.5.0-binaries-w